[tool.poetry]
name = "openstack-cli"
version = "0.1.0"
description = ""
authors = ["Benjamin Genèze <benjamin.geneze@orange.com>"]

[tool.poetry.dependencies]
python = "^3.10"
aodhclient = "3.3.0"
appdirs = "1.4.4"
attrs = "23.1.0"
autopage = "0.5.1"
Babel = "2.12.1"
"backports.entry-points-selectable" = "^1.2.0"
certifi = "2023.7.22"
cffi = "1.15.1"
charset-normalizer = "3.2.0"
cliff = "4.3.0"
cmd2 = "2.4.3"
cryptography = "40.0.2"
debtcollector = "2.5.0"
decorator = "5.1.1"
distlib = "^0.3.7"
docker = "6.1.3"
"dogpile.cache" = "1.2.2"
fasteners = "0.19"
filelock = "^3.12.4"
futurist = "2.4.1"
gnocchiclient = "7.0.8"
idna = "3.4"
importlib-metadata = "6.8.0"
iso8601 = "2.0.0"
jmespath = "1.0.1"
jsonpatch = "1.33"
jsonpointer = "2.4"
jsonschema = "4.19.0"
jsonschema-specifications = "2023.7.1"
keystoneauth1 = "5.3.0"
msgpack = "1.0.5"
murano-pkg-check = "0.3.0"
netaddr = "0.9.0"
netifaces = "0.11.0"
networkx = "3.1"
openstackclient = "4.0.0"
openstacksdk = "1.5.0"
os-client-config = "2.1.0"
os-service-types = "1.7.0"
osc-lib = "2.8.1"
"oslo.concurrency" = "5.2.0"
"oslo.config" = "9.2.0"
"oslo.context" = "5.2.0"
"oslo.i18n" = "6.1.0"
"oslo.log" = "5.3.0"
"oslo.serialization" = "5.2.0"
"oslo.utils" = "6.2.1"
osprofiler = "4.1.0"
otcextensions = "0.30.3"
packaging = "23.1"
pbr = "5.11.1"
platformdirs = "^3.10.0"
ply = "3.11"
prettytable = "0.7.2"
pycparser = "2.21"
pydot = "1.4.2"
pyinotify = "0.9.6"
pyOpenSSL = "23.2.0"
pyparsing = "3.1.1"
pyperclip = "1.8.2"
python-barbicanclient = "5.6.0"
python-cinderclient = "9.4.0"
python-congressclient = "2.0.1"
python-dateutil = "2.8.2"
python-designateclient = "5.3.0"
python-glanceclient = "4.4.0"
python-heatclient = "3.3.0"
python-ironic-inspector-client = "5.0.0"
python-ironicclient = "5.4.0"
python-keystoneclient = "5.2.0"
python-mistralclient = "5.1.0"
python-muranoclient = "2.7.0"
python-neutronclient = "11.0.0"
python-novaclient = "18.4.0"
python-octaviaclient = "3.5.0"
python-openstackclient = "6.3.0"
python-saharaclient = "4.2.0"
python-searchlightclient = "2.1.1"
python-senlinclient = "3.1.0"
python-swiftclient = "4.4.0"
python-troveclient = "8.2.1"
python-vitrageclient = "4.8.0"
python-watcherclient = "4.2.0"
python-zaqarclient = "2.6.0"
python-zunclient = "4.7.0"
pytz = "2023.3.post1"
PyYAML = "6.0.1"
referencing = "0.30.2"
requests = "2.31.0"
requestsexceptions = "1.4.0"
rfc3986 = "2.0.0"
rpds-py = "0.10.3"
semantic-version = "2.10.0"
simplejson = "3.19.1"
six = "^1.16.0"
stevedore = "5.1.0"
typing-extensions = "4.8.0"
tzdata = "2023.3"
ujson = "5.8.0"
urllib3 = "2.0.5"
warlock = "2.0.1"
wcwidth = "0.2.6"
WebOb = "1.8.7"
websocket-client = "1.6.3"
wrapt = "1.15.0"
yaql = "2.0.0"
zipp = "3.17.0"
maturin = "^1.2.3"
setuptools = "^68.2.2"
setuptools-rust = "^1.7.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
