[tool.poetry]
name = "openstack-cli"
version = "0.1.0"
description = ""
authors = ["Xavier Maillard <xavier.maillard@orange.com>"]

[tool.poetry.dependencies]
python = "^3.10"
aodhclient = "3.0.0"
appdirs = "1.4.4"
attrs = "22.1.0"
autopage = "0.5.1"
Babel = "2.10.3"
"backports.entry-points-selectable" = "^1.1.1"
certifi = "2022.6.15"
cffi = "1.15.1"
charset-normalizer = "2.1.1"
cliff = "4.0.0"
cmd2 = "2.4.2"
cryptography = "37.0.4"
debtcollector = "2.5.0"
decorator = "5.1.1"
distlib = "^0.3.6"
docker = "6.0.0"
"dogpile.cache" = "1.1.8"
fasteners = "0.17.3"
filelock = "^3.8.0"
futurist = "2.4.1"
gnocchiclient = "7.0.7"
idna = "3.3"
importlib-metadata = "4.12.0"
iso8601 = "1.0.2"
jmespath = "1.0.1"
jsonpatch = "1.32"
jsonpointer = "2.3"
jsonschema = "4.15.0"
keystoneauth1 = "5.0.0"
monotonic = "1.6"
msgpack = "1.0.4"
munch = "2.5.0"
murano-pkg-check = "0.3.0"
netaddr = "0.8.0"
netifaces = "0.11.0"
networkx = "2.8.6"
openstackclient = "4.0.0"
openstacksdk = "0.101.0"
os-client-config = "2.1.0"
os-service-types = "1.7.0"
osc-lib = "2.6.2"
"oslo.concurrency" = "5.0.0"
"oslo.config" = "9.0.0"
"oslo.context" = "5.0.0"
"oslo.i18n" = "5.1.0"
"oslo.log" = "5.0.0"
"oslo.serialization" = "5.0.0"
"oslo.utils" = "6.0.1"
osprofiler = "3.4.3"
otcextensions = "0.28.1"
packaging = "21.3"
pbr = "5.10.0"
platformdirs = "^2.5.2"
ply = "3.11"
prettytable = "0.7.2"
pycparser = "2.21"
pydot = "1.4.2"
pyinotify = "0.9.6"
pyOpenSSL = "22.0.0"
pyparsing = "3.0.9"
pyperclip = "1.8.2"
pyrsistent = "0.18.1"
python-barbicanclient = "5.4.0"
python-cinderclient = "9.1.0"
python-congressclient = "2.0.1"
python-dateutil = "2.8.2"
python-designateclient = "5.0.0"
python-glanceclient = "4.0.1"
python-heatclient = "3.0.0"
python-ironic-inspector-client = "4.8.0"
python-ironicclient = "5.0.1"
python-keystoneclient = "5.0.0"
python-mistralclient = "4.4.0"
python-muranoclient = "2.4.1"
python-neutronclient = "8.1.0"
python-novaclient = "18.0.0"
python-octaviaclient = "3.0.0"
python-openstackclient = "6.0.0"
python-saharaclient = "4.0.0"
python-searchlightclient = "2.1.1"
python-senlinclient = "2.5.0"
python-swiftclient = "4.0.1"
python-troveclient = "7.3.0"
python-vitrageclient = "4.6.0"
python-watcherclient = "3.4.0"
python-zaqarclient = "2.3.0"
python-zunclient = "4.5.0"
pytz = "2022.2.1"
PyYAML = "6.0"
requests = "2.28.1"
requestsexceptions = "1.4.0"
rfc3986 = "2.0.0"
semantic-version = "2.10.0"
simplejson = "3.17.6"
six = "^1.16.0"
stevedore = "4.0.0"
ujson = "5.4.0"
urllib3 = "1.26.12"
warlock = "2.0.1"
wcwidth = "0.2.5"
WebOb = "1.8.7"
websocket-client = "1.4.0"
wrapt = "1.14.1"
yaql = "2.0.0"
zipp = "3.8.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
