# Generated by: toolbox make-shell pkgs.niv
let
  toolboxSrc = builtins.fromJSON (builtins.readFile ./toolbox.json);
  toolbox = import (builtins.fetchTarball {
    url = "https://github.com/Caascad/toolbox/archive/${toolboxSrc.commit}.tar.gz";
    sha256 = toolboxSrc.sha256;
  }) {};

in with toolbox; pkgs.runCommand "deps" {
  buildInputs = [
    pkgs.niv pkgs.act
    (pkgs.python3.withPackages (p: [p.pyaml p.graphqlclient]))
  ];
} ""
