#!/usr/bin/env bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

_continue() {
  read -p "Continue [y/n]: " -n 1 -r
  echo
  [[ $REPLY =~ ^[Yy]$ ]] || exit 1
}

echo
echo "## Toolbox needs to be migrated !"
echo
echo "The installation process of the toolbox has changed since you have installed it."
echo
echo "The install script needs to be run again."
echo
echo "If you already have done the migration you may have forgotten to remove"
echo "the toolbox alias in your bashrc."
echo
_continue
echo

"$DIR"/install

echo
echo "## Migration complete !"
echo
echo "You need to remove the toolbox alias of your .bashrc !"
echo
echo "The toolbox script is now installed in your environment as any other tool."
echo
