# List of packages that will be ignored during the update process
blacklist:
  - nixpkgs
  - concourse_6_4_1
  - concourse_7_3_2
  - velero
# Map of mappings used as aliases when triggering a nix build. Key is se beginning  of the package name, Value is the "-A" argument to "nix-build"
build_mappings:
  terraform-provider: terraform-providers
  kubespy: kubectl-plugins.spy
  kail: kubectl-plugins.tail
  ksniff: kubectl-plugins.sniff
  kubectl-topology: kubectl-plugins.topology
  ketall: kubectl-plugins.ketall
  helm-diff: helm-plugins.diff
