name: Build terraform providers derivations

on:
  pull_request:
    paths:
      - '**.nix'
      - 'nix/*'
      - 'pkgs/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest macos-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: cachix/install-nix-action@v25
    - name: Setup binary cache
      uses: cachix/cachix-action@v14
      with:
        name: toolbox
        skipPush: true
    - name: Build terraform providers
      run: nix-build -A terraform-providers
      env:
        NIXPKGS_ALLOW_UNFREE: 1
