name: Build

on:
  pull_request:
    paths:
      - '**.nix'
      - 'nix/*'
      - 'pkgs/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Install Nix
      uses: cachix/install-nix-action@v18
    - name: Setup binary cache
      uses: cachix/cachix-action@v12
      with:
        name: toolbox
        skipPush: true
    - name: Build
      run: nix-build
    - name: Build terraform providers
      run: nix-build -A terraform-providers
