name: Publish

on:
  push:
    branches:
      - master
    paths:
      - '**.nix'
      - 'nix/*'

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v14.1
    - name: Setup binary cache
      uses: cachix/cachix-action@v10
      with:
        name: toolbox
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Build
      run: nix-build
    - name: Build terraform providers
      run: nix-build -A terraform-providers
