name: Publish other derivations

on:
  push:
    branches:
      - master
    paths:
      - '**.nix'
      - 'nix/*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: cachix/install-nix-action@v31
    - name: Setup binary cache
      uses: cachix/cachix-action@v16
      with:
        name: toolbox
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Build
      run: nix-build
      env:
        NIXPKGS_ALLOW_UNFREE: 1
