name: Test

on:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: toolbox test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install toolbox
      run: ./install https://github.com/${GITHUB_REPOSITORY}/archive/${GITHUB_SHA}.tar.gz
    - name: Doctor
      run: |
        . /home/${USER}/.nix-profile/etc/profile.d/nix.sh
        toolbox doctor
    - name: List tools
      run: |
        . /home/${USER}/.nix-profile/etc/profile.d/nix.sh
        toolbox list
    - name: Install / Uninstall tool
      run: |
        . /home/${USER}/.nix-profile/etc/profile.d/nix.sh
        toolbox install jq
        toolbox uninstall jq
    - name: Make and update shell
      run: |
        . /home/${USER}/.nix-profile/etc/profile.d/nix.sh
        cd $(mktemp -d)
        toolbox make-shell jq
        nix-shell --command 'jq --help'
        toolbox update-shell ${GITHUB_SHA}
        nix-shell --run 'jq --help'
    - name: Make terraform shell
      run: |
        . /home/${USER}/.nix-profile/etc/profile.d/nix.sh
        cd $(mktemp -d)
        SHELL_COMMIT=${GITHUB_SHA} toolbox make-terraform-shell vault flexibleengine null
        cat <<EOF >main.tf
        resource null_resource foo {}
        EOF
        nix-shell --run "terraform init && terraform plan"
      env:
        NIXPKGS_ALLOW_UNFREE: 1
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: bewuethr/shellcheck-action@v2
